version: '3'
services:
  proxy:
    image: traefik
    command: --api --docker --docker.domain=bacon.lol --logLevel=DEBUG
    networks:
      - webgateway
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - /etc/traefik/acme.json:/acme.json
    labels:
      traefik.enable: "false"

  bacon.lol: 
    build: .
    networks:
      - webgateway
    ports:
      - 80
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:bacon.lol"

networks:
  webgateway:
    driver: bridge
